package com.progressterra.ipbandroidapi.api.suggestion.model

data class SuggestionExtendedData(
    val area: String = "",
    val areaFiasId: String = "",
    val areaKladrId: String = "",
    val block: String = "",
    val city: String = "",
    val cityDistrict: String = "",
    val cityDistrictFiasId: String = "",
    val cityDistrictKladrId: String = "",
    val cityFiasId: String = "",
    val cityKladrId: String = "",
    val country: String = "",
    val entrance: String = "",
    val flat: String = "",
    val floor: String = "",
    val geoLat: String = "",
    val geoLon: String = "",
    val house: String = "",
    val houseFiasId: String = "",
    val houseKladrId: String = "",
    val kladrId: String = "",
    val postalCode: String = "",
    val region: String = "",
    val regionFiasId: String = "",
    val regionKladrId: String = "",
    val regionType: String = "",
    val street: String = "",
    val streetFiasId: String = "",
    val streetKladrId: String = ""
) {

    internal constructor(data: SuggestionExtendedRaw?) : this(
        data?.area ?: "",
        data?.areaFiasId ?: "",
        data?.areaKladrId ?: "",
        data?.block ?: "",
        data?.city ?: "",
        data?.cityDistrict ?: "",
        data?.cityDistrictFiasId ?: "",
        data?.cityDistrictKladrId ?: "",
        data?.cityFiasId ?: "",
        data?.cityKladrId ?: "",
        data?.country ?: "",
        data?.entrance ?: "",
        data?.flat ?: "",
        data?.floor ?: "",
        data?.geoLat ?: "",
        data?.geoLon ?: "",
        data?.house ?: "",
        data?.houseFiasId ?: "",
        data?.houseKladrId ?: "",
        data?.kladrId ?: "",
        data?.postalCode ?: "",
        data?.region ?: "",
        data?.regionFiasId ?: "",
        data?.regionKladrId ?: "",
        data?.regionType ?: "",
        data?.street ?: "",
        data?.streetFiasId ?: "",
        data?.streetKladrId ?: ""
    )
}
