package com.progressterra.ipbandroidapi.api.iecommerce.cart.model

import com.google.gson.annotations.SerializedName

data class SaleHeadData(
    val adressString: String,
    val beginTimeService: String,
    val commentClient: String,
    val currentPositionInCashCahnge: Int,
    val dateClose: String,
    val dateCollection: String,
    val dateConfirm: String,
    val dateCustomerReceived: String,
    val dateDoc: String,
    val dateStartProcessingDelivery: String,
    val dateSync: String,
    val dateSyncWithExternalERP: String,
    val dateToSend: String,
    val dateTranssferToSend: String,
    val drComment: List<DrComment>,
    val drMetaDHSaleHead: List<DrMetaDHSaleHead>,
    val drSaleRow: List<DrSaleRow>,
    val endTimeService: String,
    val fDocumentNumber: Int,
    val fiscalCheckFD: String,
    val fiscalCheckFN: String,
    val fiscalCheckFP: String,
    val fiscalCheckNumber: Int,
    val idBayer: String,
    val idEmployyeCourier: String,
    val idEmployyeOrderPicker: String,
    val idEnterprise: String,
    val idExtDataAddress: String,
    val idExternalERP: String,
    val idPreSale: String,
    val idUnique: String,
    val idrfCashier: String,
    val idrfShop: String,
    val idrgCashChange: String,
    val indexCount: Int,
    val levelOfSatisfaction: Int,
    val mode: Int,
    val number: String,
    val posted: String,
    val postedAddBonuses: String,
    val postedWritingBonuses: String,
    val reasonLevelOfSatisfaction: String,
    val statusObject: Int,
    val statusOrder: Int,
    val systemLevelOfSatisfaction: Int,
    val typeSaleReturn: Int
)
