package com.progressterra.ipbandroidapi.api.ambassador.model

data class AmbassadorData(
    val address: String,
    val bankAccountDetails: BankAccountDetailsData,
    val dataForDirectPayment: String,
    val dateGPH: String,
    val dateLastUpdate: String,
    val dateOfBirth: String,
    val idAmbassadorClient: String,
    val idEnterprise: String,
    val idOfficerConfirmation: String,
    val idUnique: String,
    val idrfTypeCooperation: String,
    val jsonDataBankAccountDetails: String,
    val name: String,
    val numberGPH: String,
    val officialData: String,
    val passportGet: String,
    val passportNumber: String,
    val passportSerial: String,
    val patronicName: String,
    val queryStatusWork: Int,
    val soname: String,
    val stateAmbassador: Int,
    val statusWork: Int,
    val tin: String,
    val urlImageContractGPH: String,
    val urlImagePassport: String,
    val urlImageSNILS: String
) {

    internal constructor(data: AmbassadorDataRaw?) : this(
        data?.address ?: "",
        BankAccountDetailsData(data?.bankAccountDetails),
        data?.dataForDirectPayment ?: "",
        data?.dateGPH ?: "",
        data?.dateLastUpdate ?: "",
        data?.dateOfBirth ?: "",
        data?.idAmbassadorClient ?: "",
        data?.idEnterprise ?: "",
        data?.idOfficerConfirmation ?: "",
        data?.idUnique ?: "",
        data?.idrfTypeCooperation ?: "",
        data?.jsonDataBankAccountDetails ?: "",
        data?.name ?: "",
        data?.numberGPH ?: "",
        data?.officialData ?: "",
        data?.passportGet ?: "",
        data?.passportNumber ?: "",
        data?.passportSerial ?: "",
        data?.patronicName ?: "",
        data?.queryStatusWork ?: 0,
        data?.soname ?: "",
        data?.stateAmbassador ?: 0,
        data?.statusWork ?: 0,
        data?.tin ?: "",
        data?.urlImageContractGPH ?: "",
        data?.urlImagePassport ?: "",
        data?.urlImageSNILS ?: ""
    )
}
