package com.progressterra.ipbandroidapi.api.iecommerce.cart.model

data class SaleHeadData(
    val adressString: String,
    val beginTimeService: String,
    val commentClient: String,
    val currentPositionInCashCahnge: Int,
    val dateClose: String,
    val dateCollection: String,
    val dateConfirm: String,
    val dateCustomerReceived: String,
    val dateDoc: String,
    val dateStartProcessingDelivery: String,
    val dateSync: String,
    val dateSyncWithExternalERP: String,
    val dateToSend: String,
    val dateTranssferToSend: String,
    val drComment: List<CommentData>,
    val drMetaDHSaleHead: List<MetaSaleHeadData>,
    val drSaleRow: List<SaleRowData>,
    val endTimeService: String,
    val fDocumentNumber: Int,
    val fiscalCheckFD: String,
    val fiscalCheckFN: String,
    val fiscalCheckFP: String,
    val fiscalCheckNumber: Int,
    val idBayer: String,
    val idEmployyeCourier: String,
    val idEmployyeOrderPicker: String,
    val idEnterprise: String,
    val idExtDataAddress: String,
    val idExternalERP: String,
    val idPreSale: String,
    val idUnique: String,
    val idrfCashier: String,
    val idrfShop: String,
    val idrgCashChange: String,
    val indexCount: Int,
    val levelOfSatisfaction: Int,
    val mode: Int,
    val number: String,
    val posted: String,
    val postedAddBonuses: String,
    val postedWritingBonuses: String,
    val reasonLevelOfSatisfaction: String,
    val statusObject: Int,
    val statusOrder: Int,
    val systemLevelOfSatisfaction: Int,
    val typeSaleReturn: Int
) {

    internal constructor(data: DhSaleHead?) : this(
        data?.adressString ?: "",
        data?.beginTimeService ?: "",
        data?.commentClient ?: "",
        data?.currentPositionInCashCahnge ?: 0,
        data?.dateClose ?: "",
        data?.dateCollection ?: "",
        data?.dateConfirm ?: "",
        data?.dateCustomerReceived ?: "",
        data?.dateDoc ?: "",
        data?.dateStartProcessingDelivery ?: "",
        data?.dateSync ?: "",
        data?.dateSyncWithExternalERP ?: "",
        data?.dateToSend ?: "",
        data?.dateTranssferToSend ?: "",
        data?.drComment?.map { CommentData(it) } ?: emptyList(),
        data?.drMetaDHSaleHead?.map { MetaSaleHeadData(it) } ?: emptyList(),
        data?.drSaleRow?.map { SaleRowData(it) } ?: emptyList(),
        data?.endTimeService ?: "",
        data?.fDocumentNumber ?: 0,
        data?.fiscalCheckFD ?: "",
        data?.fiscalCheckFN ?: "",
        data?.fiscalCheckFP ?: "",
        data?.fiscalCheckNumber ?: 0,
        data?.idBayer ?: "",
        data?.idEmployyeCourier ?: "",
        data?.idEmployyeOrderPicker ?: "",
        data?.idEnterprise ?: "",
        data?.idExtDataAddress ?: "",
        data?.idExternalERP ?: "",
        data?.idPreSale ?: "",
        data?.idUnique ?: "",
        data?.idrfCashier ?: "",
        data?.idrfShop ?: "",
        data?.idrgCashChange ?: "",
        data?.indexCount ?: 0,
        data?.levelOfSatisfaction ?: 0,
        data?.mode ?: 0,
        data?.number ?: "",
        data?.posted ?: "",
        data?.postedAddBonuses ?: "",
        data?.postedWritingBonuses ?: "",
        data?.reasonLevelOfSatisfaction ?: "",
        data?.statusObject ?: 0,
        data?.statusOrder ?: 0,
        data?.systemLevelOfSatisfaction ?: 0,
        data?.typeSaleReturn ?: 0
    )
}
