package com.progressterra.ipbandroidapi.api.iecommerce.cart.model

data class SaleRowData(
    val barcodeCodeGoods: String,
    val basePrice: Int,
    val beginPrice: Double,
    val datePickingFirst: String,
    val datePickingSecond: String,
    val defectName: String,
    val dhSaleHead: SaleHeadData,
    val drAddedBonus: List<AddedBonusData>,
    val drDiscountPosition: List<DiscountPositionData>,
    val drPaymentPositionSale: List<PaymentPositionSaleData>,
    val drPaymentRowBonus: List<PaymentRowBonusData>,
    val endPrice: Double,
    val idDiscountBasisForBeginPrice: String,
    val idFeature: String,
    val idSeller: String,
    val idUnique: String,
    val iddhSaleHead: String,
    val iddrRetrun: String,
    val iddrSaleForReturn: String,
    val idrfNomnclatura: String,
    val idrfReasonReturn: String,
    val idrgGoodsInventory: String,
    val imageJSONData: String,
    val indexInCheck: Int,
    val kiz: String,
    val nameGoods: String,
    val priceCost: Int,
    val reasonReturnText: String,
    val saleType: Int
) {

    internal constructor(data: DrSaleRow?) : this(
        data?.barcodeCodeGoods ?: "",
        data?.basePrice ?: 0,
        data?.beginPrice ?: 0.0,
        data?.datePickingFirst ?: "",
        data?.datePickingSecond ?: "",
        data?.defectName ?: "",
        SaleHeadData(data?.dhSaleHead),
        data?.drAddedBonus?.map { AddedBonusData(it) } ?: emptyList(),
        data?.drDiscountPosition?.map { DiscountPositionData(it) } ?: emptyList(),
        data?.drPaymentPositionSale?.map { PaymentPositionSaleData(it) } ?: emptyList(),
        data?.drPaymentRowBonus?.map { PaymentRowBonusData(it) } ?: emptyList(),
        data?.endPrice ?: 0.0,
        data?.idDiscountBasisForBeginPrice ?: "",
        data?.idFeature ?: "",
        data?.idSeller ?: "",
        data?.idUnique ?: "",
        data?.iddhSaleHead ?: "",
        data?.iddrRetrun ?: "",
        data?.iddrSaleForReturn ?: "",
        data?.idrfNomnclatura ?: "",
        data?.idrfReasonReturn ?: "",
        data?.idrgGoodsInventory ?: "",
        data?.imageJSONData ?: "",
        data?.indexInCheck ?: 0,
        data?.kiz ?: "",
        data?.nameGoods ?: "",
        data?.priceCost ?: 0,
        data?.reasonReturnText ?: "",
        data?.saleType ?: 0
    )
}
