package com.progressterra.ipbandroidapi.api.iecommerce.core.model

data class RGGoodsInventoryExtData(
    val idUnique: String,
    val name: String,
    val extendedDescription: String,
    val artikul: String,
    val idEnterprise: String,
    val url: String,
    val imageDataJSON: String,
    val additionalDataJSON: String,
    val idCategory: String,
    val popularOrder: Int,
    val rating: Float,
    val barcode: String,
    val idDiscountBasisForBeginPrice: String,
    val idFeature: String,
    val nameFeature: String,
    val defectName: String,
    val kiz: String,
    val additionaInfo: String,
    val lastTimeUpdate: String,
    val idrfNomenclatura: String,
    val idrfShop: String,
    val quantity: Int,
    val beginPrice: Double,
    val currentPrice: Double,
    val costPrice: Double,
    val costtPriceBasicUnit: Double,
    val maxValueDiscount: Double,
    val idrfPlace: String,
    val colorName: String,
    val idrfColor: String,
    val countInCart: Int
) {

    internal constructor(data: RGGoodsInventoryExtRaw?) : this(
        data?.idUnique ?: "",
        data?.name ?: "",
        data?.extendedDescription ?: "",
        data?.artikul ?: "",
        data?.idEnterprise ?: "",
        data?.url ?: "",
        data?.imageDataJSON ?: "",
        data?.additionalDataJSON ?: "",
        data?.idCategory ?: "",
        data?.popularOrder ?: 0,
        data?.rating ?: 0F,
        data?.barcode ?: "",
        data?.idDiscountBasisForBeginPrice ?: "",
        data?.idFeature ?: "",
        data?.nameFeature ?: "",
        data?.defectName ?: "",
        data?.kiz ?: "",
        data?.additionaInfo ?: "",
        data?.lastTimeUpdate ?: "",
        data?.idrfNomenclatura ?: "",
        data?.idrfShop ?: "",
        data?.quantity ?: 0,
        data?.beginPrice ?: 0.0,
        data?.currentPrice ?: 0.0,
        data?.costPrice ?: 0.0,
        data?.costtPriceBasicUnit ?: 0.0,
        data?.maxValueDiscount ?: 0.0,
        data?.idrfPlace ?: "",
        data?.colorName ?: "",
        data?.idrfColor ?: "",
        data?.countInCart ?: 0
    )
}
