/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.progressterra.ipbandroidapi.api.application.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param result 
 * @param `data` 
 * @param totalNumberRecords 
 */


data class RGApplicationViewModelResultData (

    @SerializedName("result")
    val result: ResultOperation? = null,

    @SerializedName("data")
    val `data`: RGApplicationViewModel? = null,

    @SerializedName("totalNumberRecords")
    val totalNumberRecords: kotlin.Int? = null

)

