/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.progressterra.ipbandroidapi.api.application.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param fieldName 
 * @param variantSort 
 */


data class SortData (

    @SerializedName("fieldName")
    val fieldName: kotlin.String? = null,

    @SerializedName("variantSort")
    val variantSort: TypeVariantSort? = null

)

