/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.progressterra.ipbandroidapi.api.application.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * Values: SUCCESS,WARNING,ERROR_SERVER,ERROR_AUTH,ERROR_ACCESS
 */

enum class StatusResult(val value: kotlin.String) {

    @SerializedName(value = "success")
    SUCCESS("success"),

    @SerializedName(value = "warning")
    WARNING("warning"),

    @SerializedName(value = "errorServer")
    ERROR_SERVER("errorServer"),

    @SerializedName(value = "errorAuth")
    ERROR_AUTH("errorAuth"),

    @SerializedName(value = "errorAccess")
    ERROR_ACCESS("errorAccess");
}

