/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.progressterra.ipbandroidapi.api.application.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * Values: EQUALS_STRONG,EQUALS_IGNORE_CASE,CONTAINS_STRONG,CONTAINS_IGNORE_CASE
 */

enum class TypeComparison(val value: kotlin.String) {

    @SerializedName(value = "equalsStrong")
    EQUALS_STRONG("equalsStrong"),

    @SerializedName(value = "equalsIgnoreCase")
    EQUALS_IGNORE_CASE("equalsIgnoreCase"),

    @SerializedName(value = "containsStrong")
    CONTAINS_STRONG("containsStrong"),

    @SerializedName(value = "containsIgnoreCase")
    CONTAINS_IGNORE_CASE("containsIgnoreCase");
}

