/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.progressterra.ipbandroidapi.api.application.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * Values: ASC,DESC
 */

enum class TypeVariantSort(val value: kotlin.String) {

    @SerializedName(value = "asc")
    ASC("asc"),

    @SerializedName(value = "desc")
    DESC("desc");
}

