/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RFCharacteristicTypeViewModel
import org.openapitools.client.models.RFCharacteristicValueViewModel

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param characteristicType 
 * @param characteristicValue 
 */


data class CharacteristicData (

    @SerializedName("characteristicType")
    val characteristicType: RFCharacteristicTypeViewModel? = null,

    @SerializedName("characteristicValue")
    val characteristicValue: RFCharacteristicValueViewModel? = null

)

