/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FieldForFilter
import org.openapitools.client.models.SortData

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param listFields 
 * @param sort 
 * @param searchData 
 * @param skip 
 * @param take 
 */


data class FilterAndSort (

    @SerializedName("listFields")
    val listFields: kotlin.collections.List<FieldForFilter>? = null,

    @SerializedName("sort")
    val sort: SortData? = null,

    @SerializedName("searchData")
    val searchData: kotlin.String? = null,

    @SerializedName("skip")
    val skip: kotlin.Int? = null,

    @SerializedName("take")
    val take: kotlin.Int? = null

)

