/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.TypeSize

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param url 
 * @param sizeType 
 * @param width 
 * @param height 
 * @param propertySize 
 */


data class InfoImage (

    @SerializedName("url")
    val url: kotlin.String? = null,

    @SerializedName("sizeType")
    val sizeType: TypeSize? = null,

    @SerializedName("width")
    val width: kotlin.Int? = null,

    @SerializedName("height")
    val height: kotlin.Int? = null,

    @SerializedName("size")
    val propertySize: kotlin.Long? = null

)

