/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Данные по предоставленной рассрочке
 *
 * @param countMonthPayment Количество месяцев, на которое дается расрочка
 * @param amountPaymentInMonth Сумма оплаты в месяц
 */


data class InstallmentPlan (

    /* Количество месяцев, на которое дается расрочка */
    @SerializedName("countMonthPayment")
    val countMonthPayment: kotlin.Int? = null,

    /* Сумма оплаты в месяц */
    @SerializedName("amountPaymentInMonth")
    val amountPaymentInMonth: kotlin.Double? = null

)

