/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.InfoImage

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param listInfoImage 
 */


data class ListInfoImage (

    @SerializedName("listInfoImage")
    val listInfoImage: kotlin.collections.List<InfoImage>? = null

)

