/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CharacteristicData
import org.openapitools.client.models.InstallmentPlan
import org.openapitools.client.models.RFNomenclatureViewModel
import org.openapitools.client.models.RGGoodsInventoryViewModel

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param nomenclature 
 * @param inventoryData 
 * @param listProductCharacteristic Список характеристик товара
 * @param installmentPlanValue 
 * @param countInCart 
 */


data class ProductView (

    @SerializedName("nomenclature")
    val nomenclature: RFNomenclatureViewModel? = null,

    @SerializedName("inventoryData")
    val inventoryData: RGGoodsInventoryViewModel? = null,

    /* Список характеристик товара */
    @SerializedName("listProductCharacteristic")
    val listProductCharacteristic: kotlin.collections.List<CharacteristicData>? = null,

    @SerializedName("installmentPlanValue")
    val installmentPlanValue: InstallmentPlan? = null,

    @SerializedName("countInCart")
    val countInCart: kotlin.Int? = null

)

