/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.StatusResult

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param status 
 * @param message 
 * @param messageDev 
 * @param codeResult 
 * @param duration 
 * @param idLog 
 * @param xRequestId 
 */


data class ResultOperation (

    @SerializedName("status")
    val status: StatusResult? = null,

    @SerializedName("message")
    val message: kotlin.String? = null,

    @SerializedName("messageDev")
    val messageDev: kotlin.String? = null,

    @SerializedName("codeResult")
    val codeResult: kotlin.Int? = null,

    @SerializedName("duration")
    val duration: kotlin.Double? = null,

    @SerializedName("idLog")
    val idLog: java.util.UUID? = null,

    @SerializedName("x-request-id")
    val xRequestId: kotlin.String? = null

)

