/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name 
 * @param dataInJSON Произвольные данные характеристики  Например, это может быть ссылка на таблицу размеров, если это характеристика размеров
 */


data class RFCharacteristicTypeEntity (

    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Произвольные данные характеристики  Например, это может быть ссылка на таблицу размеров, если это характеристика размеров */
    @SerializedName("dataInJSON")
    val dataInJSON: kotlin.String? = null

)

