/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idrfCharacteristicType Характеристика, к которой относится значение
 * @param valueAsString Строковое значение характеристики
 * @param valueAsNumber Числовое значение характеристики
 * @param valueAsDate 
 * @param valueAsJSON Специфические данные значения характеристики
 */


data class RFCharacteristicValueEntity (

    /* Характеристика, к которой относится значение */
    @SerializedName("idrfCharacteristicType")
    val idrfCharacteristicType: java.util.UUID? = null,

    /* Строковое значение характеристики */
    @SerializedName("valueAsString")
    val valueAsString: kotlin.String? = null,

    /* Числовое значение характеристики */
    @SerializedName("valueAsNumber")
    val valueAsNumber: kotlin.Double? = null,

    @SerializedName("valueAsDate")
    val valueAsDate: kotlin.String? = null,

    /* Специфические данные значения характеристики */
    @SerializedName("valueAsJSON")
    val valueAsJSON: kotlin.String? = null

)

