/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idrfCharacteristicType Характеристика, к которой относится значение
 * @param valueAsString Строковое значение характеристики
 * @param valueAsNumber Числовое значение характеристики
 * @param valueAsDate 
 * @param valueAsJSON Специфические данные значения характеристики
 * @param idUnique Уникальный идентификатор
 * @param idEnterprise Идентификатор организации, которой принадлежит данная запись
 * @param dateAdded Дата добавления записи
 * @param dateUpdated Дата обновления записи
 * @param dateSoftRemoved Если дата установлена, то сущность помечена на удаление. Физически данные не удаляются  Функции Delete лишь помечают сущность на удаление устанавливая дату вызова метода
 * @param viewData Как представляем характеристику по умолчанию
 */


data class RFCharacteristicValueViewModel (

    /* Характеристика, к которой относится значение */
    @SerializedName("idrfCharacteristicType")
    val idrfCharacteristicType: java.util.UUID? = null,

    /* Строковое значение характеристики */
    @SerializedName("valueAsString")
    val valueAsString: kotlin.String? = null,

    /* Числовое значение характеристики */
    @SerializedName("valueAsNumber")
    val valueAsNumber: kotlin.Double? = null,

    @SerializedName("valueAsDate")
    val valueAsDate: kotlin.String? = null,

    /* Специфические данные значения характеристики */
    @SerializedName("valueAsJSON")
    val valueAsJSON: kotlin.String? = null,

    /* Уникальный идентификатор */
    @SerializedName("idUnique")
    val idUnique: java.util.UUID? = null,

    /* Идентификатор организации, которой принадлежит данная запись */
    @SerializedName("idEnterprise")
    val idEnterprise: java.util.UUID? = null,

    /* Дата добавления записи */
    @SerializedName("dateAdded")
    val dateAdded: kotlin.String? = null,

    /* Дата обновления записи */
    @SerializedName("dateUpdated")
    val dateUpdated: kotlin.String? = null,

    /* Если дата установлена, то сущность помечена на удаление. Физически данные не удаляются  Функции Delete лишь помечают сущность на удаление устанавливая дату вызова метода */
    @SerializedName("dateSoftRemoved")
    val dateSoftRemoved: kotlin.String? = null,

    /* Как представляем характеристику по умолчанию */
    @SerializedName("viewData")
    val viewData: kotlin.String? = null

)

