/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RGEntitytMediaDataViewModel

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idrfSpecification Идентификатор спецификации, которой принадлежит данная номенклатура
 * @param name Наиименование - может задаваться вручную или генерироваться на основе правил
 * @param idUnique Уникальный идентификатор
 * @param idEnterprise Идентификатор организации, которой принадлежит данная запись
 * @param dateAdded Дата добавления записи
 * @param dateUpdated Дата обновления записи
 * @param dateSoftRemoved Если дата установлена, то сущность помечена на удаление. Физически данные не удаляются  Функции Delete лишь помечают сущность на удаление устанавливая дату вызова метода
 * @param listCatalogCategory Список категорий в которых присутствует номенклатура
 * @param listImages Список изображений
 * @param popularOrder Порядок вывода товара по популярности
 * @param rating Рейтинг товара
 */


data class RFNomenclatureViewModel (

    /* Идентификатор спецификации, которой принадлежит данная номенклатура */
    @SerializedName("idrfSpecification")
    val idrfSpecification: java.util.UUID? = null,

    /* Наиименование - может задаваться вручную или генерироваться на основе правил */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Уникальный идентификатор */
    @SerializedName("idUnique")
    val idUnique: java.util.UUID? = null,

    /* Идентификатор организации, которой принадлежит данная запись */
    @SerializedName("idEnterprise")
    val idEnterprise: java.util.UUID? = null,

    /* Дата добавления записи */
    @SerializedName("dateAdded")
    val dateAdded: kotlin.String? = null,

    /* Дата обновления записи */
    @SerializedName("dateUpdated")
    val dateUpdated: kotlin.String? = null,

    /* Если дата установлена, то сущность помечена на удаление. Физически данные не удаляются  Функции Delete лишь помечают сущность на удаление устанавливая дату вызова метода */
    @SerializedName("dateSoftRemoved")
    val dateSoftRemoved: kotlin.String? = null,

    /* Список категорий в которых присутствует номенклатура */
    @SerializedName("listCatalogCategory")
    val listCatalogCategory: kotlin.collections.List<java.util.UUID>? = null,

    /* Список изображений */
    @SerializedName("listImages")
    val listImages: kotlin.collections.List<RGEntitytMediaDataViewModel>? = null,

    /* Порядок вывода товара по популярности */
    @SerializedName("popularOrder")
    val popularOrder: kotlin.Int? = null,

    /* Рейтинг товара */
    @SerializedName("rating")
    val rating: kotlin.Double? = null

)

