/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idrfSpecification Идентификатор спецификации, которой принадлежит данная номенклатура
 * @param name Наиименование - может задаваться вручную или генерироваться на основе правил
 */


data class RFNomenclatureEntity (

    /* Идентификатор спецификации, которой принадлежит данная номенклатура */
    @SerializedName("idrfSpecification")
    val idrfSpecification: java.util.UUID? = null,

    /* Наиименование - может задаваться вручную или генерироваться на основе правил */
    @SerializedName("name")
    val name: kotlin.String? = null

)

