/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idrfCatalogCategory Идентификатор категории каталога
 * @param idrfNomenclature Идентификатор номенклатуры
 */


data class RGCatalogProductEntity (

    /* Идентификатор категории каталога */
    @SerializedName("idrfCatalogCategory")
    val idrfCatalogCategory: java.util.UUID? = null,

    /* Идентификатор номенклатуры */
    @SerializedName("idrfNomenclature")
    val idrfNomenclature: java.util.UUID? = null

)

