/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idrfNomenclature Идентификатор номенклатуры
 * @param idrfCharacteristicValue Значение характеристики
 */


data class RGProductCharacteristicEntity (

    /* Идентификатор номенклатуры */
    @SerializedName("idrfNomenclature")
    val idrfNomenclature: java.util.UUID? = null,

    /* Значение характеристики */
    @SerializedName("idrfCharacteristicValue")
    val idrfCharacteristicValue: java.util.UUID? = null

)

