/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param idrfSpecification 
 * @param idrfCharacteristicType Тип характеристики, которая присутствует в спецификации продукта
 * @param isMandatory Признак обязательной характеристики, которую нужно обязательно заоплнить
 */


data class RGSpecificationCharacteristicTypeEntity (

    @SerializedName("idrfSpecification")
    val idrfSpecification: java.util.UUID? = null,

    /* Тип характеристики, которая присутствует в спецификации продукта */
    @SerializedName("idrfCharacteristicType")
    val idrfCharacteristicType: java.util.UUID? = null,

    /* Признак обязательной характеристики, которую нужно обязательно заоплнить */
    @SerializedName("isMandatory")
    val isMandatory: kotlin.Boolean? = null

)

