/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * Values: success,warning,errorServer,errorAuth,errorAccess
 */

enum class StatusResult(val value: kotlin.String) {

    @SerializedName(value = "success")
    success("success"),

    @SerializedName(value = "warning")
    warning("warning"),

    @SerializedName(value = "errorServer")
    errorServer("errorServer"),

    @SerializedName(value = "errorAuth")
    errorAuth("errorAuth"),

    @SerializedName(value = "errorAccess")
    errorAccess("errorAccess");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is StatusResult) "$data" else null

        /**
         * Returns a valid [StatusResult] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): StatusResult? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

