/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Тип размера
 *
 * Values: original,small,medium,large
 */

enum class TypeSize(val value: kotlin.String) {

    @SerializedName(value = "original")
    original("original"),

    @SerializedName(value = "small")
    small("small"),

    @SerializedName(value = "medium")
    medium("medium"),

    @SerializedName(value = "large")
    large("large");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TypeSize) "$data" else null

        /**
         * Returns a valid [TypeSize] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TypeSize? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

